browser: EDGE
environment: stage

environments:
  test:
    envName: test
    appUrl: https://www.selenium.dev/
    expectedTitle: Selenium

  stage:
    envName: stage
    appUrl: https://playwright.dev/
    expectedTitle: Fast and reliable end-to-end testing for modern web apps | Playwright

  prod:
    envName: prod
    appUrl: https://www.cypress.io/
    expectedTitle: JavaScript Component Testing and E2E Testing Framework | Cypress
